import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import StickyHeader from "@/components/header/StickyHeader";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "NGC - Nature Guru Creations",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased flex flex-col min-h-screen`}
      >
        <header>
          <StickyHeader />
        </header>
        <main className="grow pt-20 w-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
